name: Build and Release app

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
          channel: "stable"

      - name: Build Android apps
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          flutter build appbundle

      - name: Save android packages
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/*
            build/app/outputs/bundle/release/*

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all build outputs
        uses: actions/download-artifact@v3
        with:
          path: exec/

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ExCode
          prerelease: true
          generate_release_notes: true
          files: |
            exec/android/bundle/release/app-release.aab
            exec/android/flutter-apk/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/exptrack
